---
deployment:
      tasks:
       - export DEPLOYPATH=/home/restroworld/public_html/uat
       - export REPOPATH=/home/restroworld/repositories/restroworld-New-FrontEnd-Project-uat
       - /bin/rm -Rf ${DEPLOYPATH}
       - /bin/rsync -aP --exclude '.git' --exclude '.well-known' ${REPOPATH}/ ${DEPLOYPATH} --delete-after
       - /bin/chmod 755 ${DEPLOYPATH}
       - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 '{}' \;
       - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 '{}' \;
       - /bin/cp -R dist/* $DEPLOYPATH

